//! Converts EasyEDA's OBJ 3D model to a VRML (`.wrl`) file KiCad can show.
//!
//! A port of easyeda2kicad's `export_kicad_3d_model.py`. The model is centred
//! on the footprint origin, sits on the board at z = 0, is moved by
//! EasyEDA's placement offset, and is scaled from mm to VRML's 0.1 inch unit.
//! The STEP model is saved as EasyEDA sends it.

use std::collections::HashMap;

use regex::Regex;
use std::sync::LazyLock;

use crate::easyeda::model3d::Ee3dModel;
use crate::easyeda::values::py_float;
use crate::pyfmt::{dedent, repr, round_digits, split_lines};

const VRML_HEADER: &str = "#VRML V2.0 utf8\n# 3D model generated by easyeda2kicad.py (https://github.com/uPesy/easyeda2kicad.py)\n";

static MATERIAL: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)newmtl .*?endmtl").expect("valid pattern"));

#[derive(Default)]
struct Material {
    ambient: Option<Vec<String>>,
    diffuse: Option<Vec<String>>,
    specular: Option<Vec<String>>,
    transparency: Option<String>,
}

fn materials(obj: &str) -> HashMap<String, Material> {
    let mut out = HashMap::new();
    for block in MATERIAL.find_iter(obj) {
        let mut material = Material::default();
        let mut id = None;
        for line in split_lines(block.as_str()) {
            let values: Vec<String> = line
                .split_whitespace()
                .skip(1)
                .map(str::to_string)
                .collect();
            if line.starts_with("newmtl") {
                id = values.first().cloned();
            } else if line.starts_with("Ka") {
                material.ambient = Some(values);
            } else if line.starts_with("Kd") {
                material.diffuse = Some(values);
            } else if line.starts_with("Ks") {
                material.specular = Some(values);
            } else if line.starts_with("d ") {
                // EasyEDA's `d` is already a transparency (0 opaque, 1 clear),
                // which is what VRML means by transparency.
                material.transparency = Some(
                    values
                        .first()
                        .and_then(|v| py_float(v))
                        .map_or_else(|| "0".to_string(), |v| repr(round_digits(v, 4))),
                );
            }
        }
        if let Some(id) = id {
            out.insert(id, material);
        }
    }
    out
}

fn vertex_coordinates(obj: &str) -> Vec<[f64; 3]> {
    split_lines(obj)
        .into_iter()
        .filter_map(|line| {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() < 4 || parts[0] != "v" {
                return None;
            }
            Some([
                py_float(parts[1])?,
                py_float(parts[2])?,
                py_float(parts[3])?,
            ])
        })
        .collect()
}

/// Whether the VRML text holds a number a viewer cannot read, which is what
/// an unreadable vertex becomes.
pub fn has_unreadable_number(wrl: &str) -> bool {
    wrl.split(|c: char| c.is_whitespace() || c == ',')
        .any(super::sexpr::is_non_finite)
}

/// The VRML text for a model, or `None` when the OBJ has no geometry with a
/// known material.
pub fn to_wrl(model: &Ee3dModel, obj: &str) -> Option<String> {
    let materials = materials(obj);
    let coordinates = vertex_coordinates(obj);

    // Centre X and Y on the origin and put the bottom at z = 0, then apply
    // EasyEDA's placement offset, which is already in mm like the OBJ.
    let (mut offset_x, mut offset_y, mut offset_z) = (0.0, 0.0, 0.0);
    if let Some(first) = coordinates.first() {
        let mut min = *first;
        let mut max = *first;
        for v in &coordinates[1..] {
            for axis in 0..3 {
                if v[axis] < min[axis] {
                    min[axis] = v[axis];
                }
                if v[axis] > max[axis] {
                    max[axis] = v[axis];
                }
            }
        }
        offset_x = -(min[0] + max[0]) / 2.0;
        offset_y = -(min[1] + max[1]) / 2.0;
        offset_z = -min[2];
    }
    offset_x += model.translation.x;
    offset_y += model.translation.y;
    offset_z += model.translation.z;

    let vertices: Vec<String> = coordinates
        .iter()
        .map(|[x, y, z]| {
            [(x + offset_x), (y + offset_y), (z + offset_z)]
                .map(|v| repr(round_digits(v / 2.54, 4)))
                .join(" ")
        })
        .collect();

    let shapes: Vec<&str> = obj.split("usemtl").skip(1).collect();
    if shapes.is_empty() {
        return None;
    }

    let mut wrl = VRML_HEADER.to_string();
    for shape in shapes {
        let lines = split_lines(shape);
        let material_name = lines
            .first()
            .map(|l| l.replace(' ', ""))
            .unwrap_or_default();
        let Some(material) = materials.get(&material_name) else {
            continue;
        };

        let mut index_of: HashMap<i64, usize> = HashMap::new();
        let mut coord_index = String::new();
        let mut points: Vec<&str> = Vec::new();
        for line in lines.iter().skip(1) {
            let mut tokens = line.split_whitespace();
            if tokens.next() != Some("f") {
                continue;
            }
            let mut face = Vec::new();
            for token in tokens {
                let index: i64 = token.split('/').next().unwrap_or("").parse().ok()?;
                let local = match index_of.get(&index) {
                    Some(&local) => local,
                    None => {
                        // OBJ indices count from 1. Python's list indexing
                        // reads 0 and negatives from the end, as here.
                        let position = if index >= 1 {
                            index - 1
                        } else {
                            vertices.len() as i64 + index - 1
                        };
                        let vertex = usize::try_from(position)
                            .ok()
                            .and_then(|p| vertices.get(p))?;
                        let local = points.len();
                        points.push(vertex.as_str());
                        index_of.insert(index, local);
                        local
                    }
                };
                face.push(local.to_string());
            }
            face.push("-1".to_string());
            coord_index.push_str(&face.join(","));
            coord_index.push(',');
        }

        // VRML's ambient intensity is one number: the luminance of Ka.
        let ambient = material
            .ambient
            .clone()
            .unwrap_or_else(|| vec!["0.2".into(), "0.2".into(), "0.2".into()]);
        let ambient_intensity = match (
            ambient.first().and_then(|v| py_float(v)),
            ambient.get(1).and_then(|v| py_float(v)),
            ambient.get(2).and_then(|v| py_float(v)),
        ) {
            (Some(r), Some(g), Some(b)) => repr(round_digits(0.299 * r + 0.587 * g + 0.114 * b, 4)),
            _ => repr(0.2),
        };
        let transparency = material
            .transparency
            .clone()
            .unwrap_or_else(|| "0".to_string());
        let diffuse = material
            .diffuse
            .as_ref()
            .map_or("0.8 0.8 0.8".to_string(), |c| c.join(" "));
        let specular = material
            .specular
            .as_ref()
            .map_or("0 0 0".to_string(), |c| c.join(" "));

        let shape_text = format!(
            "\n            Shape{{\n                appearance Appearance {{\n                    material  Material \t{{\n                        diffuseColor {diffuse}\n                        specularColor {specular}\n                        ambientIntensity {ambient_intensity}\n                        transparency {transparency}\n                        shininess 0.5\n                    }}\n                }}\n                geometry IndexedFaceSet {{\n                    ccw TRUE\n                    solid FALSE\n                    coord DEF co Coordinate {{\n                        point [\n                            {}\n                        ]\n                    }}\n                    coordIndex [\n                        {coord_index}\n                    ]\n                }}\n            }}",
            points.join(", "),
        );
        wrl.push_str(&dedent(&shape_text));
    }
    Some(wrl)
}
